### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Felleus** [woutzah/ChatBrawl#5]
[12:06:13 ERROR]: Could not pass event PlayerLoginEvent to ChatBrawl v1.7.1
java.lang.NullPointerException: null
at be.woutzah.chatbrawl.messages.Printer.getCurrentRunningRaceInfo(Printer.java:163) ~[?:?]
at be.woutzah.chatbrawl.listeners.GeneralListener.notifyOnLogin(GeneralListener.java:22) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-251]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.joinWorld(AbstractLoginListenerPlay.java:138) ~[?:?]
at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.lambda$finishLogin$1(AbstractLoginListenerPlay.java:90) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1311) ~[patched_1.16.3.jar:git-Paper-251]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-251]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-251]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by wouter-blockken** [comment]
It looks like you're running an older version of the plugin on a 1.16.3 instance. Downloading the latest update 1.7.2 will fix your problem. If not let me know!
